era5:
  dataset: "reanalysis-era5-single-levels"
  product_type: "reanalysis"
  bounding_box: [35, 65, 5, 95]
  variables:
    - "10m_u_component_of_wind"
    - "10m_v_component_of_wind"
    - "2m_dewpoint_temperature"
    - "2m_temperature"
    - "total_precipitation"
  parameters:
    - "u10"
    - "v10"
    - "d2m"
    - "t2m"
    - "tp"
  download_format: "zip"
  data_format: "netcdf"

span:
  year_start: 2000
  year_end: 2024

paths:
  compressed: "data/compressed"
  raw: "data/raw"
  interim: "data/interim"
  processed: "data/processed"

eda:
  u10:
    min: -24.724151611328125
    max: 25.767061233520508
    mean: 1.0826175212860107
  v10:
    min: -24.77762794494629
    max: 26.513349533081055
    mean: 0.1734369993209839
  d2m:
    min: 220.58026123046875
    max: 304.7151794433594
    mean: 288.31121826171875
  t2m:
    min: 230.87396240234375
    max: 317.87042236328125
    mean: 295.1584777832031
  tp:
    min: 0.0
    max: 700.979248046875
    mean: 3.298840284347534

post_processing:
  dim_size:
    - time: 9132
    - latitude: 121
    - longitude: 121
  target: "concurrent_extreme"
  features:
    - "u10"
    - "v10"
    - "d2m"

# refer NOTES.md for more information